 <?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('album', array('action' => 'add')));
 $form->prepare();
 if ($notification){
     echo "New album <b>".$notification['title']."</b> by <b>".$notification['artist']."</b> added";
 }


 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'))." ";
 echo $this->formRow($form->get('artist'))." ";
 echo $this->formSubmit($form->get('submit'))." ";
  echo $this->formSubmit($form->get('submit2'));
 echo $this->form()->closeTag();
 ?>