<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'album',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();
 if ($notification){
     echo "New album title - <b>".$notification['title']."</b>, new artist - <b>".$notification['artist']."</b><br><br>";
 }
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'))." ";
 echo $this->formRow($form->get('artist'))." ";
 echo $this->formSubmit($form->get('submit'))." ";
 echo $this->formSubmit($form->get('submit2'));
 echo $this->form()->closeTag();