<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit Album';
 $this->headTitle($title);
 ?>
<style>
    body {
        background-color: #efefef;
    }
    .logoutbutton{
        float: right;
    }
    .width{
        width: 400px;        
    }
</style>
 <h1><?php echo $this->escapeHtml($title); ?>
 <a class = 'logoutbutton btn btn-danger' href = "<?php echo $this->url('album',array('action'=>'logout')); ?>">Logout</a>
 </h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('album',array(
     'action' => 'edit',
     'id'     => $this->id,
     )
 ));
 $form->setAttribute('class','width');
 $form->prepare();
 if ($notification){
     echo "<div class = 'alert alert-success'>New title - <b>".$notification['title']."</b>, New artist - <b>".$notification['artist']."</b><br><br></div>";
 }
 echo $this->form()->openTag($form);
 
 echo $this->formHidden($form->get('id'));
 
 echo $this->formLabel($form->get('title'))."<br>";
 echo $this->formText($form->get('title'))."<br><br>";
 
 echo $this->formLabel($form->get('artist'))."<br>";
 echo $this->formText($form->get('artist'))."<br><br>";
 $form->get('submit')->setAttribute('class','btn btn-primary');
 echo $this->formSubmit($form->get('submit'))." ";
 echo $this->formSubmit($form->get('submit2'));
 echo $this->form()->closeTag();