<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>

<table class="table">
     <tr>
         <th><a href="<?php echo $this->url('album',
                     array('action' => 'index', 'sort' => 'title'));?>">Title</a></th>
         <th><a href="<?php echo $this->url('album',
                     array('action' => 'index', 'sort' => 'artist'));?>">Artist</a></th>
         <th></th>
         <th></th>
     </tr>
     <?php foreach ($this->paginator as $album) : // <-- change here! ?>
         <tr>
             <td><?php echo $this->escapeHtml($album->title);?></td>
             <td><?php echo $this->escapeHtml($album->artist);?></td>
             <td>
                 <a href="<?php echo $this->url('album',
                     array('action' => 'edit', 'id' => $album->id));?>">Edit</a>
             </td>
             <td>
                 <a href="<?php echo $this->url('album',
                     array('action' => 'delete', 'id' => $album->id));?>">Delete</a>
             </td>
         </tr>
     <?php endforeach; ?>
 </table>
  <?php
  echo $this->paginationControl(
          $this->paginator,
          'sliding',
          array('partial/paginator.phtml', 'Album'),
          array(
              'route' => 'album'
          )
          );
  
 ?>