<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My Albums';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
 </p>
 <?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'index')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formInput($form->get('search'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<table class="table">
     <tr>
         <th><a href="<?php
         if ($request[search]){
             echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=id&order=".($request['ord']['id']+1)."&search=".$request[search];
         } else {
             echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=id&order=".($request['ord']['id']+1);
         }
         ?>">Id</a></th>
         <th><a href="<?php
         if ($request[search]){
             echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=title&order=".($request['ord']['title']+1)."&search=".$request[search];
         } else {
             echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=title&order=".($request['ord']['title']+1);
         }
         ?>">Title</a></th>
         <th><a href="<?php
         if ($request[search]){
             echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=artist&order=".($request['ord']['artist']+1)."&search=".$request[search];
         } else {
             echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=artist&order=".($request['ord']['artist']+1);
         }
         ?>">Artist</a></th>
         <th></th>
         <th></th>
     </tr>
     <?php foreach ($this->paginator as $album) : ?>
         <tr>
             <td><?php echo $this->escapeHtml($album->id);?></td>
             <td><?php echo $this->escapeHtml($album->title);?></td>
             <td><?php echo $this->escapeHtml($album->artist);?></td>
             <td>
                 <a href="<?php echo $this->url('album',
                     array('action' => 'edit', 'id' => $album->id));?>">Edit</a>
             </td>
             <td>
                 <a href="<?php echo $this->url('album',
                     array('action' => 'delete', 'id' => $album->id));?>">Delete</a>
             </td>
         </tr>
     <?php endforeach; 
     
     ?>
 </table>
  <?php
  echo $this->paginationControl(
          $this->paginator,
          'sliding',
          array('partial/paginator.phtml', 'Album'),
          array(
              'route' => 'album',
              'sort' => $request['sort'],
              'order' => $request['order'],
              'search' =>$request['search']
              
          )
          );
