<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My Albums';
 $this->headTitle($title);
 ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<style>
    a.disabled {
        cursor: not-allowed;
        pointer-events: none;
        
    }
    .active{
        font-size: 17px;
    }
    #a{
        color: white;
    }
    #x{
        width: 400px;
        float:left;
    }
</style>
 <h1><?php echo $this->escapeHtml($title); ?><a class = 'col-sm-offset-7 btn btn-danger' href = "<?php echo $this->url('album',array('action'=>'logout')); ?>">Logout</a></h1>
 
 <?php
 $acl = $this->acl;
 $role = $this->role;
 
 
 if (!$request['page']){
     $request['page']=1;
 }
 if ($request['del']){
     echo "<div class = 'alert alert-danger'>Album <b>".$request['del']."</b> deleted</div>";        
 }
 if($acl->isAllowed($role, null, 'add')){
     echo "<a href = ".$this->url('album', array('action'=>'add'))." id ='a'><div class = 'btn btn-primary'>Create New Album</div></a><br><br>";
 } else{
     echo "<a class ='disabled' href = ".$this->url('album', array('action'=>'index'))." id ='a'><div class = 'btn btn-primary'>Create New Album</div></a><br><br>";
 }
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'index')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formInput($form->get('search'))." ";

$form->get('submit')->setAttribute('class','btn btn-success');

echo " ".$this->formSubmit($form->get('submit'))." ";
if($request['search']){
    echo "<a class = 'btn btn-danger' href = '".$this->url('album', array('action' => 'index'))."'>Cancel</a>";
}
echo $this->form()->closeTag();

?>
 <br>
<table class="table table-striped">
     <tr>
         <th><a href="<?php
         echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=id&order=".($request['ord']['id']+1);
         if ($request[search]){
             echo "&search=".$request[search];
         }
         ?>">Id</a></th>
         <th><a href="<?php
         echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=title&order=".($request['ord']['title']+1);
         if ($request['search']){
             echo "&search=".$request['search'];
         }
         ?>">Title</a></th>
         <th><a href="<?php
         echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=artist&order=".($request['ord']['artist']+1);
         if ($request['search']){
             echo "&search=".$request['search'];
         }
         ?>">Artist</a></th>
         <th></th>
         <th></th>
     </tr>
     <?php foreach ($this->paginator as $album) : ?>
         <tr>
             <td><?php echo $this->escapeHtml($album->id);?></td>
             <td><?php echo $this->escapeHtml($album->title);?></td>
             <td><?php echo $this->escapeHtml($album->artist);?></td>
             <td>
                 <?php
                 if($acl->isAllowed($role, null, 'edit')){
                     echo "<a href=".$this->url('album', array('action' => 'edit', 'id' => $album->id)).">Edit</a>";
                  }else {
                      echo 'Edit';
                  }
                 ?>
             </td>
             <td><?php
                 if($acl->isAllowed($role, null, 'delete')){
                     echo "<a href=".$this->url('album', array('action' => 'delete', 'id' => $album->id)).">Delete</a>";
                  }else {
                      echo 'Delete';
                  }
                 ?>
             </td>
         </tr>
     <?php endforeach; 
     
     ?>
 </table>
  <?php
  echo $this->paginationControl(
          $this->paginator,
          'sliding',
          array('partial/paginator.phtml', 'Album'),
          array(
              'route' => 'album',
              'sort' => $request['sort'],
              'order' => $request['order'],
              'search' =>$request['search']
              
          )
          );
  
  //$dbAdapter = new Zend\Db\Adapter\Adapter;
  //print_r($dbAdapter)  ;