<?php

 $title = 'Login';
 $this->headTitle($title);
 ?>
<style>
    .width{
        width: 400px;
    }
</style>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('album',array('action' => 'login',)));
 if ($this->message){
     echo "<div class = 'alert alert-danger'><b>".$this->message."</b></div>"; 
 }
 $form->setAttribute('class','width');
 $form->prepare();
 echo $this->form()->openTag($form);
 
 echo $this->formLabel($form->get('username'))."<br>";
 echo $this->formText($form->get('username'))."<br><br>";
 
 echo $this->formLabel($form->get('password'))."<br>";
 echo $this->formText($form->get('password'))."<br><br>";
 
 $form->get('submit')->setAttribute('class','btn btn-success');
 echo $this->formSubmit($form->get('submit'))." ";
 echo $this->form()->closeTag();