<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My Albums';
 $this->headTitle($title);
 $acl = $this->acl;
 $role = $this->role;
 ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<style>
    .dis{
        color: #888;
        cursor: not-allowed;
    }
    body {
        background-color: #efefef;
    }
    .logoutbutton{
        float: right;
    }
    .active{
        font-size: 17px;
    }
    #a{
        color: white;
    }
    #searchinput{
        width: 400px;
        float:left;
        margin-right: 5px;
    }
    #searchtable{
        margin-left: -15px;
        margin-right: 15px;
        
    }
    
</style>
 <h1>
     <?php
     echo $this->escapeHtml($title);
     ?>
     <a class = 'logoutbutton btn btn-danger' href = "<?php echo $this->url('album',array('action'=>'logout')); ?>">Logout</a></h1>
 
 <?php
 
 
 //Set default page number = 1
 if (!$request['page']){
     $request['page']=1;
 }
 //Album deleted notification
 if ($request['del']){
     echo "<div class = 'alert alert-danger'>Album <b>".$request['del']."</b> deleted</div>";        
 }
 
 //Add Create Album button
 if($acl->isAllowed($role, null, 'add')){
     echo "<a href = ".$this->url('album', array('action'=>'add'))." id ='a'><div class = 'btn btn-primary'>Create New Album</div></a><br><br>";
 } else{
     echo "<a class ='disabled btn btn-primary' href = '#' id ='a'>Create New Album</a><br><br>";
 }
 ?>
 
<input autocomplete="off" type="text" name="search" class="form-control col-xs-6 col-md-4" id="searchinput" placeholder="Enter Search Text" onfocus="this.value = this.value;" value = <?php echo $request['search']?>> 
<div id = 'searchbutton' class = "btn btn-success">Search</div>
<a id = 'cancel' class = "btn btn-danger" href = "<?php echo $this->url('album', array('action' => 'index')); ?>">Cancel</a>

 
<?php
echo $this->form()->closeTag();
?>

<br><br>
<div id = 'y'>
<table class="table table-striped">
     <tr>
         <th><a href="<?php
         echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=id&order=".($request['ord']['id']+1);
         if ($request[search]){
             echo "&search=".$request[search];
         }
         ?>">Id</a></th>
         <th><a href="<?php
         echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=title&order=".($request['ord']['title']+1);
         if ($request['search']){
             echo "&search=".$request['search'];
         }
         ?>">Title</a></th>
         <th><a href="<?php
         echo $this->url('album', array('action' => 'index'))."?page=".$request['page']."&sort=artist&order=".($request['ord']['artist']+1);
         if ($request['search']){
             echo "&search=".$request['search'];
         }
         ?>">Artist</a></th>
         <th></th>
         <th></th>
     </tr>
     <?php foreach ($this->paginator as $album) : ?>
         <tr>
             <td><?php echo $this->escapeHtml($album->id);?></td>
             <td><?php echo $this->escapeHtml($album->title);?></td>
             <td><?php echo $this->escapeHtml($album->artist);?></td>
             <td>
                 <?php
                 if($acl->isAllowed($role, null, 'edit')){
                     echo "<a href=".$this->url('album', array('action' => 'edit', 'id' => $album->id)).">Edit</a>";
                  }else {
                      echo '<span class = "dis">Edit</span>';
                  }
                 ?>
             </td>
             <td><?php
                 if($acl->isAllowed($role, null, 'delete')){
                     echo "<a href=".$this->url('album', array('action' => 'delete', 'id' => $album->id)).">Delete</a>";
                  }else {
                      echo '<span class = "dis">Delete</span>';
                  }
                 ?>
             </td>
         </tr>
     <?php endforeach; 
     
     ?>
 </table>
  <?php
  echo $this->paginationControl(
          $this->paginator,
          'sliding',
          array('partial/paginator.phtml', 'Album'),
          array(
              'route' => 'album',
              'sort' => $request['sort'],
              'order' => $request['order'],
              'search' =>$request['search']
              
          )
          );
  ?>
</div>
 <script>
     $(document).ready(function(){
         if ($("#searchinput").val() === ""){
             $("#cancel").hide();
         }
     })
     $("#searchinput").keyup(function(event){
         if(event.keyCode === 13){
             $("#searchbutton").click();
         }
         if(event.keyCode === 27){
             $("#searchinput").val("");
             $("#searchbutton").click();
             $("#cancel").hide();
         }
         
     });
     $("#searchbutton").click(function(){
         $("#cancel").show();
         $.post("/album/public/album/search",
         {
             search : $("#searchinput").val()
         },
         function(data){
             $("#y").html(data);
             $("#searchinput").focus();
             
         });
     });
</script>