<?php if (!$album): ?>
<table class = 'table table-striped'>
     <tr>
         <th>Id</th>
         <th>Title</th>
         <th>Artist</th>
     </tr>

    <?php foreach ($this->paginator as $album) : ?>
     <tr>
         <td><?php echo $this->escapeHtml($album->id);?></td>
         <td><a href = '<?php echo $this->url('album', array('action' => 'index','id' => $album->id))?>'><?php echo $this->escapeHtml($album->title);?></a></td>
         <td><?php echo $this->escapeHtml($album->artist);?></td>
         </tr>
     <?php endforeach; ?>
         
 </table>
  <?php
  echo $this->paginationControl(
          $this->paginator,
          'sliding',
          array('partial/paginator.phtml', 'Album'),
          array(
              'route' => 'album',              
          )
          );
  ?>
<?php else: ?>



<table>
     <tr>
         <th>Id</th>
         <th>Title</th>
         <th>Artist</th>
     </tr>
     <tr>
         
         <td> <?php echo $this->escapeHtml($album->id);?> </td>
         <td> <?php echo $this->escapeHtml($album->title);?> </td>
         <td> <?php echo $this->escapeHtml($album->artist);?> </td>
        
     </tr>
</table>
<?php endif; ?>
